// Auth
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const METADATA_SUCCESS = "METADATA_SUCCESS";
export const METADATA_ERROR = "METADATA_ERROR";
export const LOADING_METADATA = "LOADING_METADATA";
export const EQUITY_DATA_SUCCESS = "EQUITY_DATA_SUCCESS";
export const EQUITY_DATA_ERROR = "EQUITY_DATA_ERROR";